addressbook_index:
    path:     /
    defaults: { _controller: "AppBundle:AddressBook:index" }
    methods:  GET

addressbook_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:AddressBook:show" }
    methods:  GET

addressbook_new:
    path:     /add
    defaults: { _controller: "AppBundle:AddressBook:add" }
    methods:  [GET, POST]

addressbook_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:AddressBook:edit" }
    methods:  [GET, POST]

addressbook_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:AddressBook:delete" }
    methods:  DELETE
